ALTER SESSION SET CURRENT_SCHEMA = student;
INSERT INTO student.product (id, name, bottle_size_liters, bottles_per_package, age_restriction, alcohol_percent, product_category) VALUES (1, 'Coca Cola', 1, 12, 11,99, 0, 0, null);
CREATE TABLE STUDENT.PRODUCT
(
  ID INTEGER NOT NULL
, NAME NVARCHAR2(100) NOT NULL
, BOTTLE_SIZE_LITERS NUMBER
, BOTTLES_PER_PACKAGE INTEGER
, AGE_RESTRICTION INTEGER
, ALCOHOL_PERCENT NUMBER
, PRODUCT_CATEGORY INTEGER
, CONSTRAINT PRODUCT_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

/*
CREATE TABLE STUDENT.PRODUCT_CATEGORY
(
  ID INTEGER NOT NULL
, PARENT_ID INTEGER
, NAME VARCHAR2(100) NOT NULL
, DESCRIPTION VARCHAR2(4000)
, CONSTRAINT PRODUCT_CATEGORY_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
*/
