ALTER SESSION SET CURRENT_SCHEMA = student;


CREATE TABLE STUDENT.PRODUCT
(
  ID INTEGER NOT NULL
, NAME NVARCHAR2(100) NOT NULL
, BOTTLE_SIZE_LITERS NUMBER
, BOTTLES_PER_PACKAGE INTEGER
, PRICE_PER_PACKAGE NUMBER
, AGE_RESTRICTION INTEGER
, ALCOHOL_PERCENT NUMBER
, PRODUCT_CATEGORY INTEGER
, CONSTRAINT PRODUCT_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

CREATE TABLE STUDENT.PRODUCT_CATEGORY
(
  ID INTEGER NOT NULL
, PARENT_ID INTEGER
, NAME NVARCHAR2(100) NOT NULL
, DESCRIPTION NVARCHAR2(200)
, CONSTRAINT PRODUCT_CATEGORY_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

CREATE TABLE STUDENT.CUSTOMER
(
  ID INTEGER NOT NULL
, NAME NVARCHAR2(100) NOT NULL
, ADDRESS_CITY NVARCHAR2(100)
, ADDRESS_PLZ NUMBER(5)
, ADDRESS_STREET NVARCHAR2(100)
, ADDRESS_NO NVARCHAR2(100)
, TYPE NVARCHAR2(100)
, RATING VARCHAR(1)
, CONSTRAINT CUSTOMER_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
