ALTER SESSION SET CURRENT_SCHEMA = student;

CREATE TABLE STUDENT.PRODUCT
(
  ID INTEGER NOT NULL
, NAME VARCHAR2(100) NOT NULL
, DESCRIPTION VARCHAR2(4000)
, PRODUCT_CATEGORY INTEGER
, CONSTRAINT PRODUCT_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

CREATE TABLE STUDENT.PRODUCT_CATEGORY
(
  ID INTEGER NOT NULL
, PARENT_ID INTEGER
, NAME VARCHAR2(100) NOT NULL
, DESCRIPTION VARCHAR2(4000)
, CONSTRAINT PRODUCT_CATEGORY_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
