ALTER SESSION SET CURRENT_SCHEMA = student;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE STUDENT.PRODUCT';
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE STUDENT.PRODUCT_CATEGORY';
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
