COLUMN NAME FORMAT a30;
COLUMN DESCRIPTION FORMAT a50;
COLUMN ID FORMAT 99999;
COLUMN PRODUCT_CATEGORY FORMAT 999;
SET LINESIZE 32767;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET WRAP OFF;
SET PAGESIZE 40;
