COLUMN NAME FORMAT a30;
COLUMN DESCRIPTION FORMAT a50;
COLUMN ID FORMAT 99999;
COLUMN PRODUCT_CATEGORY FORMAT 999;
COLUMN STREET FORMAT a30;
COLUMN CITY FORMAT a20;
COLUMN PLZ FORMAT 99999;
COLUMN NO FORMAT 9999;
COLUMN TYPE FORMAT a10;
COLUMN RATING FORMAT a1;

SET LINESIZE 32767;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET WRAP OFF;
SET PAGESIZE 40;
