COLUMN NAME FORMAT a30;
COLUMN DESCRIPTION FORMAT a50;
COLUMN ID FORMAT 99999;
COLUMN PRODUCT_CATEGORY FORMAT 999;
COLUMN ADDRESS_STREET FORMAT a30;
COLUMN ADDRESS_CITY FORMAT a20;
COLUMN ADDRESS_PLZ FORMAT 99999;
COLUMN ADDRESS_NO FORMAT 9999;
COLUMN TYPE FORMAT a10;
COLUMN RATING FORMAT a1;

SET LINESIZE 32767;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET WRAP OFF;
SET PAGESIZE 40;
